newswriter/views/default.py
from newswriter.modules.editorjs import renderBlock
from newswriter.modules.imagetools import handleImageUpload, handleURL
from newswriter.models.content import Article, ImageModel, Board
from newswriter.models.permissions import ListarArticulosPermission
from newswriter.models.permissions import ActualizarArticulosPermission
from newswriter.models.permissions import PonerArticulosPermission
from newswriter.models.permissions import EnviarArticulosPermission
from newswriter.models import _gen_uuid
from newswriter.forms import UploadArticleForm
from newswriter import filetools, db, csrf
from newswriter.modules.export import export_article
from newswriter.modules.import_art import importItem, NotMetadataInFile
from newswriter.modules.import_art import NewVersionExits, NoAccessToBoard
from flask import Blueprint, render_template, request, current_app
from flask import send_from_directory, url_for, abort, json
from flask import Response, stream_with_context, flash
from flask_login import login_required, current_user
from flask_menu import register_menu, current_menu
import marshmallow.exceptions
from werkzeug.utils import redirect, secure_filename
from urllib.parse import urlparse
from webpreview import OpenGraph
from json.decoder import JSONDecodeError
from pathlib import Path
import datetime
import tempfile
import pathlib
import os
import zipfile

default = Blueprint('default', __name__, url_prefix='/escritorio')


@default.before_app_first_request
def setupMenus():
    # mis entradas en el sidebar
    actions = current_menu.submenu("actions.default")
    actions._text = "Escritorio"
    actions._endpoint = None
    actions._external_url = "#!"


@default.route('/', defaults={"board_name": None})
@default.route('/<board_name>')
@register_menu(default, "actions.default.index", "Mis trabajos")
@login_required
def index(board_name):
    page = request.args.get('page', 1, type=int)
    if board_name is None:
        board = Board.getUserBoard(current_user)
    else:
        board = Board.query.get_or_404(board_name)

        # asegurarse de que el usuario puede leer este board
        if ListarArticulosPermission(board.name).can() is False:
            flash(f"Usted no tiene acceso al board {board_name}")
            return redirect(url_for('.index'))

    articulos = Article.query.filter(
        Article.board_id == board.name).order_by(
            Article.created_on.desc()).paginate(page, per_page=4)

    return render_template(
        'default/index.html',
        results=articulos, board=board,
        is_personal=("_ub" in board.name)
    )


@default.route('/escribir', defaults={"pkid": None})
@default.route('/escribir/<pkid>')
@register_menu(default, "actions.default.write", "Escribir")
@login_required
def write(pkid):
    if pkid is None:
        pkid = _gen_uuid()

    article = Article.query.get(pkid)

    # Si el articulo exite el usuario necesita permisos para modificarlo
    if article:
        if ActualizarArticulosPermission(article.board_id).can() is False:
            flash("Usted no puede hacer cambios")
            return redirect(url_for('.index', board_name=article.board_id))
    # --

    return render_template('default/write.html', pkid=pkid, article=article)


@default.route('/importar', methods=['GET', 'POST'])
@register_menu(default, "actions.default.import_article", "Importar")
@login_required
def import_article():
    """Seleccionar paquete a importar"""
    form = UploadArticleForm()

    if form.validate_on_submit():
        f = form.archive.data
        filename = secure_filename(f.filename)
        fullname = os.path.join(tempfile.mkdtemp(), filename)
        f.save(fullname)

        try:
            art = importItem(
                fullname, current_app.config['UPLOAD_FOLDER'],
                current_user)
            flash("Articulo importado")
            return redirect(url_for(".preview", pkid=art.id))
        except marshmallow.exceptions.ValidationError as e:
            flash(f"Error en el formato del archivo {e}")
        except NoAccessToBoard:
            flash("No tienes permiso para reemplazar el articulo")
            current_app.logger.exception(
                "No tienes permiso para reemplazar el articulo")
        except NewVersionExits as e:
            url = url_for(".preview", pkid=e.article.id)
            current_app.logger.debug(
                f"Ya existe una versión más reciente de ese trabajo: {url}")
        except NotMetadataInFile:
            current_app.logger.exception(
                "No existe el archivo META-INFO.json")
            flash("META-INFO file missing or corruct")
        except zipfile.BadZipFile:
            current_app.logger.exception("Bad zip file")
            flash("El archivo esta corructo")
        except UnicodeDecodeError:
            current_app.logger.exception('MATA-INFO file missing or corruct')
            flash("No se puede leer el archivo")
        except JSONDecodeError:
            flash("No se puede leer el archivo")
            current_app.logger.exception('MATA-INFO file missing or corruct')
        finally:
            current_app.logger.debug("Removing uploaded file")
            filetools.safe_remove(fullname)

    return render_template('default/import_form.html', form=form)


@default.route('/preview/<pkid>')
@login_required
def preview(pkid):
    article = Article.query.get_or_404(pkid)
    return render_template('default/preview.html', article=article)


@default.route('/download/<pkid>')
@login_required
def download_article(pkid):
    article = Article.query.get_or_404(pkid)
    file_name = export_article(article)
    file_handle = open(file_name, 'rb')

    def stream_and_remove():
        yield from file_handle
        file_handle.close()
        os.remove(file_name)

    return Response(
        stream_with_context(stream_and_remove()),
        headers={
            'Content-Type': 'application/zip',
            'Content-Disposition': 'attachment; filename="{}"'.format(
                Path(file_name).name)
        }
    )


@default.route('/assets/images/<filename>')
def uploaded_image(filename):
    folder = os.path.join(
        current_app.config['UPLOAD_FOLDER'], "images")
    return send_from_directory(folder, filename)


@default.route('/assets/<filename>')
def download_attach(filename):
    return send_from_directory(
        current_app.config['UPLOAD_FOLDER'], filename)


@default.route('/upload/photoarchive', methods=['POST'])
@login_required
def upload_photoarchive():
    """Upload a photo from photostore"""
    # check if the post request has the file part
    if 'archive' not in request.files:
        current_app.logger.debug("No file in request")
        return {"success": 0}

    # if user does not select file, browser also
    # submit an empty part without filename
    file = request.files['archive']
    if file.filename == '':
        current_app.logger.debug("Empty file name")
        return {"success": 0}

    if file and filetools.allowed_file(file.filename, {'zip'}):
        # process the zip archive here.
        filename = secure_filename(file.filename)
        fullname = os.path.join(tempfile.mkdtemp(), filename)
        file.save(fullname)
        im = None

        workdir = tempfile.TemporaryDirectory()

        try:
            with zipfile.ZipFile(fullname, 'r') as zf:
                if 'META-INFO.json' in zf.namelist():
                    zf.extractall(workdir.name)
                    # import the image here
                    metainfo_file = os.path.join(
                        workdir.name, 'META-INFO.json')
                    image_data = json.load(open(metainfo_file, 'r'))
                    if 'Photo:v1' in image_data.get('version', ''):
                        file_in_package = image_data.get('filename', None)
                        if file_in_package is None:
                            # old package version, don't include the filename
                            # asume a jpeg image
                            image_file = os.path.join(
                                workdir.name, f"{image_data.get('md5')}.jpg")
                        else:
                            image_file = os.path.join(
                                workdir.name, file_in_package)
                        im = handleImageUpload(
                            image_data.get('md5'), image_file, current_user.id,
                            current_app.config['UPLOAD_FOLDER'])
                        if im.store_data is None:
                            im.store_data = json.dumps(image_data)
                        db.session.add(im)
                        db.session.commit()
                        # --
                    else:
                        # not a photo archive or version missing
                        current_app.logger.debug(
                            "not a photo archive or version missing")
                else:
                    # Error in zip file, is this a photostore archive?
                    current_app.logger.debug("Missing archive info file")
        except zipfile.BadZipFile:
            current_app.logger.debug("Bad zip file")
        except UnicodeDecodeError:
            current_app.logger.debug('MATA-INFO file missing or corruct')
        except JSONDecodeError:
            current_app.logger.debug('MATA-INFO file missing or corruct')
        finally:
            # remove temporary files
            current_app.logger.debug("Removing temporary files")
            workdir.cleanup()
            filetools.safe_remove(fullname)

        if im is not None:

            caption = ""
            if isinstance(im.getStoreData().get('excerpt'), dict):
                blocks = im.getStoreData().get('excerpt').get('blocks')
                caption = "".join([d.get('data').get('text') for d in blocks])
            else:
                caption = im.getStoreData().get('excerpt')
            return {
                "success": 1,

newswriter/templates/editorjs/attaches.html
<div class="article--block--attaches">
    <div class="article--block--attaches--title valign-wrapper">
        <a href="{{ data.file.url }}" class="article--block--attaches--link" target="_blank">
            <i class="material-icons left">attach_file</i>
            {{ data.get('title') | safe }}
            <span class="article--block--attaches--size">
                [{{ data.file.size | filesizeformat }}]
            </span>
        </a>
    </div>
</div>

newswriter/templates/editorjs/default.html
default block render {{ type }}

newswriter/templates/editorjs/delimiter.html
<div class="article--block--delimiter"></div>

newswriter/templates/editorjs/header.html
<h{{ data.level }} class="article--block--header">{{ data.text }}</h{{ data.level }}>

newswriter/templates/editorjs/image.html
<figure class="article--block--image" data-controller="artimage">
    {% if data.file.width is gt(600) %}
    <img class="responsive-img materialboxed {% if data.file.mode %}{{ data.file.mode }}{% endif %}"
        src="{{ url_for('default.uploaded_image', filename=imageResolver(data.file.md5sum).filename) }}"
        alt="{{ data.get('caption') }}" data-artimage-target="image">
    {% else %}
    <img class="{% if data.file.mode %}{{ data.file.mode }}{% endif %} tosmall"
        src="{{ url_for('default.uploaded_image', filename=imageResolver(data.file.md5sum).filename) }}"
        alt="{{ data.get('caption') }}" data-artimage-target="image">
    {% endif %}
    <figcaption>
        {% if data.caption %}
        <span class="article--block--image--caption">{{ data.caption|safe }}</span>
        {% endif %}
        {% if data.credit %}
        {% if data.caption %} -- {% endif %}
        <span class="article--block--image--credits">{{ data.credit }}</span>
        {% endif %}
    </figcaption>
</figure>

newswriter/templates/editorjs/linkTool.html
<div class="article--block--linktool">
    <a href="{{ data.link }}" title="Abrir {{ data.link }}" target="_black">
        <img src="{{ url_for('default.uploaded_image', filename=imageResolver(data.meta.image.md5sum).filename) }}" alt="{{ data.meta.title }}" />
        <div class="article--block--linktool--title">
            {{ data.meta.title }}
        </div>
        <div class="article--block--linktool--description">
            {{ data.meta.description | truncate }}
        </div>
        {% if data.meta.site_name %}
        <div class="article--block--linktool--site">{{ data.meta.site_name }}</div>
        {% endif %}
    </a>
</div>

newswriter/templates/editorjs/list.html
<div class="article--block--list">
    {% if data.style is eq('ordered') %}
    <ol class="article--block--list--ordered">
        {% for item in data.get('items') %}
        <li>{{ item | safe }}</li>
        {% endfor %}
    </ol>
    {% else %}
    <ul class="article--block--list--unordered">
        {% for item in data.get('items') %}
        <li>{{ item | safe }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>

newswriter/templates/editorjs/paragraph.html
<p class="article--block--paragraph">
    {{ data.get('text') | safe }}
</p>

newswriter/templates/editorjs/photo.html
<figure class="article--block--photo" data-controller="artimage">
    {% if data.file.width is gt(600) %}
    <img class="responsive-img materialboxed {% if data.file.mode %}{{ data.file.mode }}{% endif %}"
        src="{{ url_for('default.uploaded_image', filename=imageResolver(data.file.md5sum).filename) }}"
        alt="{{ data.get('caption') }}" data-artimage-target="image">
    {% else %}
    <img class="{% if data.file.mode %}{{ data.file.mode }}{% endif %} tosmall"
        src="{{ url_for('default.uploaded_image', filename=imageResolver(data.file.md5sum).filename) }}"
        alt="{{ data.get('caption') }}" data-artimage-target="image">
    {% endif %}
    <figcaption>
        {% if data.caption %}
        <span class="article--block--photo--caption">{{ data.caption|safe }}</span>
        {% endif %}
        {% if data.credit %}
        {% if data.caption %} -- {% endif %}
        <span class="article--block--photo--credits">{{ data.credit }}</span>
        {% endif %}
    </figcaption>
</figure>

newswriter/templates/editorjs/quote.html
<figure class="article--block--quote {{ data.alignment }}-align">
    <blockquote class="article--block--quote--quote">
        {{ data.text | safe }}
    </blockquote>
    {% if data.caption %}
    <figcaption class="article--block--quote--source">
        {{ data.caption | safe }}
    </figcaption>
    {% endif %}
</figure>

newswriter/templates/editorjs/rawCode.html
{% if "youtube" in data.html %}
<div class="article--block--rawcode video-container">
    {{ data.html | safe }}
</div>
{% else %}
<div class="article--block--rawcode">
    {{ data.html | safe }}
</div>
{% endif %}

newswriter/templates/editorjs/warning.html
<div class="article--block--warning">
    <div class="article--block--warning--title">{{ data.title }}</div> 
    <div class="article--block--warning--message">
        {{ data.message | safe }}
    </div>
    <div class="article--block--warning--footer">
        Este mensaje no estará visible cuando se publique el articulo
    </div>
</div>