newswriter/views/default.py
from newswriter.modules.editorjs import renderBlock
from newswriter.modules.imagetools import handleImageUpload, handleURL
from newswriter.models.content import Article, ImageModel, Board
from newswriter.models.permissions import ListarArticulosPermission
from newswriter.models.permissions import ActualizarArticulosPermission
from newswriter.models.permissions import PonerArticulosPermission
from newswriter.models.permissions import EnviarArticulosPermission
from newswriter.models import _gen_uuid
from newswriter.forms import UploadArticleForm
from newswriter import filetools, db, csrf
from newswriter.modules.export import export_article
from newswriter.modules.import_art import importItem, NotMetadataInFile
from newswriter.modules.import_art import NewVersionExits, NoAccessToBoard
from flask import Blueprint, render_template, request, current_app
from flask import send_from_directory, url_for, abort, json
from flask import Response, stream_with_context, flash
from flask_login import login_required, current_user
from flask_menu import register_menu, current_menu
import marshmallow.exceptions
from werkzeug.utils import redirect, secure_filename
from urllib.parse import urlparse
from webpreview import OpenGraph
from json.decoder import JSONDecodeError
from pathlib import Path
import datetime
import tempfile
import pathlib
import os
import zipfile

default = Blueprint('default', __name__, url_prefix='/escritorio')


@default.before_app_first_request
def setupMenus():
    # mis entradas en el sidebar
    actions = current_menu.submenu("actions.default")
    actions._text = "Escritorio"
    actions._endpoint = None
    actions._external_url = "#!"


@default.route('/', defaults={"board_name": None})
@default.route('/<board_name>')
@register_menu(default, "actions.default.index", "Mis trabajos")
@login_required
def index(board_name):
    page = request.args.get('page', 1, type=int)
    if board_name is None:
        board = Board.getUserBoard(current_user)
    else:
        board = Board.query.get_or_404(board_name)

        # asegurarse de que el usuario puede leer este board
        if ListarArticulosPermission(board.name).can() is False:
            flash(f"Usted no tiene acceso al board {board_name}")
            return redirect(url_for('.index'))

    articulos = Article.query.filter(
        Article.board_id == board.name).order_by(
            Article.created_on.desc()).paginate(page, per_page=4)

    return render_template(
        'default/index.html',
        results=articulos, board=board,
        is_personal=("_ub" in board.name)
    )


@default.route('/escribir', defaults={"pkid": None})
@default.route('/escribir/<pkid>')
@register_menu(default, "actions.default.write", "Escribir")
@login_required
def write(pkid):
    if pkid is None:
        pkid = _gen_uuid()

    article = Article.query.get(pkid)

    # Si el articulo exite el usuario necesita permisos para modificarlo
    if article:
        if ActualizarArticulosPermission(article.board_id).can() is False:
            flash("Usted no puede hacer cambios")
            return redirect(url_for('.index', board_name=article.board_id))
    # --

    return render_template('default/write.html', pkid=pkid, article=article)


@default.route('/importar', methods=['GET', 'POST'])
@register_menu(default, "actions.default.import_article", "Importar")
@login_required
def import_article():
    """Seleccionar paquete a importar"""
    form = UploadArticleForm()

    if form.validate_on_submit():
        f = form.archive.data
        filename = secure_filename(f.filename)
        fullname = os.path.join(tempfile.mkdtemp(), filename)
        f.save(fullname)

        try:
            art = importItem(
                fullname, current_app.config['UPLOAD_FOLDER'],
                current_user)
            flash("Articulo importado")
            return redirect(url_for(".preview", pkid=art.id))
        except marshmallow.exceptions.ValidationError as e:
            flash(f"Error en el formato del archivo {e}")
        except NoAccessToBoard:
            flash("No tienes permiso para reemplazar el articulo")
            current_app.logger.exception(
                "No tienes permiso para reemplazar el articulo")
        except NewVersionExits as e:
            url = url_for(".preview", pkid=e.article.id)
            current_app.logger.debug(
                f"Ya existe una versión más reciente de ese trabajo: {url}")
        except NotMetadataInFile:
            current_app.logger.exception(
                "No existe el archivo META-INFO.json")
            flash("META-INFO file missing or corruct")
        except zipfile.BadZipFile:
            current_app.logger.exception("Bad zip file")
            flash("El archivo esta corructo")
        except UnicodeDecodeError:
            current_app.logger.exception('MATA-INFO file missing or corruct')
            flash("No se puede leer el archivo")
        except JSONDecodeError:
            flash("No se puede leer el archivo")
            current_app.logger.exception('MATA-INFO file missing or corruct')
        finally:
            current_app.logger.debug("Removing uploaded file")
            filetools.safe_remove(fullname)

    return render_template('default/import_form.html', form=form)


@default.route('/preview/<pkid>')
@login_required
def preview(pkid):
    article = Article.query.get_or_404(pkid)
    return render_template('default/preview.html', article=article)


@default.route('/download/<pkid>')
@login_required
def download_article(pkid):
    article = Article.query.get_or_404(pkid)
    file_name = export_article(article)
    file_handle = open(file_name, 'rb')

    def stream_and_remove():
        yield from file_handle
        file_handle.close()
        os.remove(file_name)

    return Response(
        stream_with_context(stream_and_remove()),
        headers={
            'Content-Type': 'application/zip',
            'Content-Disposition': 'attachment; filename="{}"'.format(
                Path(file_name).name)
        }
    )


@default.route('/assets/images/<filename>')
def uploaded_image(filename):
    folder = os.path.join(
        current_app.config['UPLOAD_FOLDER'], "images")
    return send_from_directory(folder, filename)


@default.route('/assets/<filename>')
def download_attach(filename):
    return send_from_directory(
        current_app.config['UPLOAD_FOLDER'], filename)


@default.route('/upload/photoarchive', methods=['POST'])
@login_required
def upload_photoarchive():
    """Upload a photo from photostore"""
    # check if the post request has the file part
    if 'archive' not in request.files:
        current_app.logger.debug("No file in request")
        return {"success": 0}

    # if user does not select file, browser also
    # submit an empty part without filename
    file = request.files['archive']
    if file.filename == '':
        current_app.logger.debug("Empty file name")
        return {"success": 0}

    if file and filetools.allowed_file(file.filename, {'zip'}):
        # process the zip archive here.
        filename = secure_filename(file.filename)
        fullname = os.path.join(tempfile.mkdtemp(), filename)
        file.save(fullname)
        im = None

        workdir = tempfile.TemporaryDirectory()

        try:
            with zipfile.ZipFile(fullname, 'r') as zf:
                if 'META-INFO.json' in zf.namelist():
                    zf.extractall(workdir.name)
                    # import the image here
                    metainfo_file = os.path.join(
                        workdir.name, 'META-INFO.json')
                    image_data = json.load(open(metainfo_file, 'r'))
                    if 'Photo:v1' in image_data.get('version', ''):
                        file_in_package = image_data.get('filename', None)
                        if file_in_package is None:
                            # old package version, don't include the filename
                            # asume a jpeg image
                            image_file = os.path.join(
                                workdir.name, f"{image_data.get('md5')}.jpg")
                        else:
                            image_file = os.path.join(
                                workdir.name, file_in_package)
                        im = handleImageUpload(
                            image_data.get('md5'), image_file, current_user.id,
                            current_app.config['UPLOAD_FOLDER'])
                        if im.store_data is None:
                            im.store_data = json.dumps(image_data)
                        db.session.add(im)
                        db.session.commit()
                        # --
                    else:
                        # not a photo archive or version missing
                        current_app.logger.debug(
                            "not a photo archive or version missing")
                else:
                    # Error in zip file, is this a photostore archive?
                    current_app.logger.debug("Missing archive info file")
        except zipfile.BadZipFile:
            current_app.logger.debug("Bad zip file")
        except UnicodeDecodeError:
            current_app.logger.debug('MATA-INFO file missing or corruct')
        except JSONDecodeError:
            current_app.logger.debug('MATA-INFO file missing or corruct')
        finally:
            # remove temporary files
            current_app.logger.debug("Removing temporary files")
            workdir.cleanup()
            filetools.safe_remove(fullname)

        if im is not None:

            caption = ""
            if isinstance(im.getStoreData().get('excerpt'), dict):
                blocks = im.getStoreData().get('excerpt').get('blocks')
                caption = "".join([d.get('data').get('text') for d in blocks])
            else:
                caption = im.getStoreData().get('excerpt')
            return {
                "success": 1,

newswriter/templates/default/boards.html
{% extends 'layout.html' %}

{% block page_title %}
Carpetas/Boards disponibles
{% endblock %}

{% block content %}
<h4>Carpetas/<em>Boards</em></h4>

<div class="row">
    <div class="col s12">
      <div class="card-panel grey lighten-3">
        <h4>
            <a href="{{ url_for('default.index') }}">
                Mis trabajos

                <span class="badge blue white-text">
                    {{ user_board.articles | length }}
                </span>
            </a>
        </h4>
      </div>
    </div>
</div>

{% for board in board_list %}
    {% if board.isPersonal() is false %}
    <div class="row">
        <div class="col s12">
          <div class="card-panel">
            <h4>
                {% if ListarArticulosPermission(board.name).can() %}
                <a href="{{ url_for('default.index', board_name=board.name) }}">
                    {{ board.name }}

                    <span class="badge blue white-text">
                        {{ board.articles | length }}
                    </span>
                </a>
                {% else %}
                <a href="#!" class="grey-text text-darken-2">
                    {{ board.name }}
                </a>
                {% endif %}
            </h4>
          </div>
        </div>
    </div>
    {% endif %}
{% endfor %}


{% endblock %}

newswriter/templates/default/import_form.html
{% extends 'layout.html' %}

{% block page_title %}{{'Importat - Redacción'}}{% endblock %}

{% block content %}
<form method="POST" enctype="multipart/form-data">
    {{ form.hidden_tag() }}
    <div class="container">
        <h3>Importar articulo</h3>
        <div class="row">
            <div class="file-field input-field col s12">
                <div class="btn">
                    <span><i class="material-icons left">file_upload</i> Archivo</span>
                    <input type="file" name="archive"
                        accept="zip,application/octet-stream,application/zip,application/x-zip,application/x-zip-compressed">
                </div>
                <div class="file-path-wrapper">
                    <input class="file-path validate" type="text">
                </div>

                {% if form.archive.errors %}
                {% for error in form.archive.errors %}
                  <p class="red-text text-darken-4">{{ error }}</p>
                {% endfor %}
                {% endif %}
            </div>
        </div>

        <div class="row">
            <div class="input-field col s12 center">
                <button class="btn waves-effect waves-light" type="submit" name="action">
                    <i class="material-icons left">send</i> enviar
                </button>
            </div>
        </div>
    </div>
</form>
{% endblock %}

newswriter/templates/default/index.html
{% if not board.isPersonal() %}
  {% extends 'layout_breadcrumbs.html' %}

  {% block breadcrumbs %}
  {{ super() }}
  <a href="{{ url_for('.list_boards') }}" class="breadcrumb">Carpetas</a>
  <a href="#!" class="breadcrumb">{{ board.name }}</a>
  {% endblock breadcrumbs %}
{% else %}
  {% extends 'layout.html' %}
{% endif %}

{% block page_title %}
  {% if is_personal %}Mis trabajos{% else %}Newswriter - {{ board.name }}{% endif %}
{% endblock %}

{% block content %}

{% if not is_personal %}
  <h4><i class="material-icons">dashboard</i> {{ board.name }}</h4>
{% else %}
  <h4><i class="material-icons">dashboard</i> Mis trabajos</h4>
{% endif %}

<div class="works-list">

  {% if results.total > 0 %}

  {% for item in results.items %}
  <div class="card">
    <div class="card-content">
      <span class="card-title"><a href="{{ url_for('.preview', pkid=item.id) }}">{{ item.headline }}</a></span>
      <p class="work-excerpt px-4">
        {% if item.excerpt %}
        {{ item.excerpt | striptags | truncate(140) }}
        {% else %}
        {{ item.getFirstTextBlock() | striptags | truncate(140) }}
        {% endif %}
      </p>
    </div>
    <div class="card-action">
      {% if ActualizarArticulosPermission(board.name).can() %}
        <a href="{{ url_for('default.write', pkid=item.id) }}">Editar</a>
      {% endif %}
      <a href="{{ url_for('.preview', pkid=item.id) }}">Ver</a>
      <a href="{{ url_for('.download_article', pkid=item.id) }}" title="Descargar articulo">Exportar</a>
      {% if EnviarArticulosPermission(board.name).can() and (local_install is false) %}
      <a href="{{ url_for('.move_article', artid=item.id) }}">Mover a ...</a>
      {% endif %}
    </div>
  </div>
  {% endfor %}

  <div class="center-align mt-5">
    <a href="{{ '#!' if results.has_prev is false else url_for('.index', page=results.prev_num)}}"
      class="waves-effect waves-light btn {{ 'disabled' if results.has_prev is false else ''}}"><i
        class="material-icons left">chevron_left</i> Anterior</a>
    <a href="{{ '#!' if results.has_next is false else url_for('.index', page=results.next_num)}}"
      class="waves-effect waves-light btn ml-5 {{ 'disabled' if results.has_next is false else ''}}">Siguiente <i
        class="material-icons right">chevron_right</i></a>
  </div>
  {% else %}
  <div class="card">
    <div class="card-content">
      <span class="card-title center-align">
        No se encontró ningún artículo
      </span>
      <div class="card-action">
        <a href="{{ url_for('default.write') }}">Escribir uno</a>
      </div>
    </div>
  </div>
  {% endif %}
</div>
{% endblock %}

newswriter/templates/default/move_article.html
{% extends 'layout.html' %}

{% block page_title %}
Carpetas/Boards disponibles
{% endblock %}

{% block content %}
<h4>Selecione destino:</h4>

{% for board in board_list %}
    {% if board.isPersonal() is false %}
    <div class="row">
        <div class="col s12">
          <div class="card-panel">
            <h4>
                <a href="{{ url_for('.move_article', artid=article.id, board_name=board.name) }}">
                    {{ board.name }}
                </a>
            </h4>
          </div>
        </div>
    </div>
    {% endif %}
{% endfor %}

{% endblock %}

newswriter/templates/default/preview.html
{% if article %}
  {% extends 'layout.html' if article.board.isPersonal() else 'layout_breadcrumbs.html' %}

  {% block breadcrumbs %}
  {{ super() }}
  <a href="{{ url_for('.list_boards') }}" class="breadcrumb">Carpetas</a>
  <a href="{{ url_for('.index', board_name=article.board.name) }}" class="breadcrumb">{{ article.board.name }}</a>
  <a href="#!" class="breadcrumb">{{ article.headline }}</a>
  {% endblock breadcrumbs %}
{% else %}
  {% extends 'layout.html' %}
{% endif %}

{% block content %}

<article class="article--item">
    <header class="article--header">
        <h1 class="article--title">{{ article.headline }}</h1>
        <aside>
            <p class="article--credits">Por {{ article.credit_line }}</p>
            <p class="article--date" data-controller="fecha"
                data-fecha-momento-value="{{ article.created_on.isoformat() }}" data-fecha-formato-value="ll">
                {{ article.created_on.isoformat() }}
            </p>
        </aside>
    </header>
    <!-- article content -->
    <div class="article--content">
        {% for b in article.getDecodedContent().get('blocks') %}
        <div class="article--block">
            {{ renderBlock(b)|safe }}
        </div>
        {% endfor %}

        <div class="fixed-action-btn" data-controller="fab">
            <a class="btn-floating btn-large red" href="{{ url_for('.write', pkid=article.id) }}"
                title="Editar articulo">
                <i class="large material-icons">mode_edit</i>
            </a>
            <ul>
                <li><a class="btn-floating"  href="{{ url_for('.download_article', pkid=article.id) }}" title="Descargar articulo"><i class="material-icons">cloud_download</i></a></li>
            </ul>
        </div>
    </div>
    <!-- article footer -->
    <footer class="article--footer">
    </footer>
</article>

{% endblock %}

newswriter/templates/default/write.html
{% if article %}
  {% extends 'layout.html' if article.board.isPersonal() else 'layout_breadcrumbs.html' %}

  {% block breadcrumbs %}
  {{ super() }}
  <a href="{{ url_for('.list_boards') }}" class="breadcrumb">Carpetas</a>
  <a href="{{ url_for('.index', board_name=article.board.name) }}" class="breadcrumb">{{ article.board.name }}</a>
  <a href="#!" class="breadcrumb">{{ article.headline }}</a>
  {% endblock breadcrumbs %}
{% else %}
  {% extends 'layout.html' %}
{% endif %}

{% block page_title %}{{'Escribir - Redacción' if article is none else article.headline}}{% endblock %}

{% block content %}
<div data-controller="editor" data-editor-author-value="{{ current_user.name }}"
  data-editor-apiendpoint-value="{{ url_for('default.articleEndPoint', pkid=pkid) }}"
  data-editor-imageupload-value="{{ url_for('default.upload_image') }}"
  data-editor-imagefetchurl-value="{{ url_for('default.fetch_image') }}"
  data-editor-linkendpoint-value="{{ url_for('default.fetch_link') }}"
  data-editor-photoupload-value="{{ url_for('default.upload_photoarchive') }}"
  data-editor-attachupload-value="{{ url_for('default.upload_attach') }}"
  data-editor-csrf-value="{{ csrf_token() }}">

  <div class="row">
    <div class="input-field col s12">
      <input class="validate" data-editor-target="headline" type="text" placeholder="Título" />
    </div>
  </div>

  <div class="row">
    <div class="input-field  col s12 m12 l6 xl6">
      <input type="text" data-editor-target="creditline" value="" />
    </div>
    <div class="col s12 m12 l6 xl6">
      <div class="chips chips-placeholder" data-editor-target="tags"></div>
      <span class="helper-text" data-error="wrong" data-success="right">
        Ingrese la palabra clave y presione <code class="grey darken-3 white-text p-1">enter</code>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
        <div class="input-field col s12">
          <textarea data-editor-target="summary" name="summary" id="summary_f" class="materialize-textarea"></textarea>
          <label for="summary_f" class="active">Resumen</label>
          <span class="helper-text" data-error="wrong" data-success="right">
            Escriba el resumen del trabajo. Si no se proporciona se usará el primer párrafo del texto
          </span>
        </div>
      </div>
  </div>


  <div id="editorContent" data-editor-target="content" class="browser-default-uls flow-text mt-5">
  </div>

  <div class="fixed-action-btn editor-tool-box" data-editor-target="toolbox">
    <a class="btn-floating btn-large disabled" data-action="editor#guardar" title="Guardar">
      <i class="large material-icons">save</i>
    </a>
    <ul>
      <li><a class="btn-floating red darken-2 disabled" title="Borrar"><i class="material-icons">delete</i></a></li>
      <li><a class="btn-floating" href="{{ url_for('.preview', pkid=pkid) }}" title="Vista previa"><i class="material-icons">pageview</i></a></li>
      <li><a class="btn-floating"  href="{{ url_for('.download_article', pkid=pkid) }}" title="Descargar articulo"><i class="material-icons">cloud_download</i></a></li>
    </ul>
  </div>

</div>
{% endblock %}